### PR TITLE
Upgrade to 5.0.0 and buster

### PR DESCRIPTION
**Pull request by dkess**

### CODE REVIEW

**Review by emmatyping — APPROVED** [review]

**Review by cg505 — APPROVED** [review]
Assuming tested.

**Comment by dkess** [comment]
I didn't test this but the release notes don't mention any instructions for upgrading to the new version. We can test in prod #YOLO

**Comment by cg505** [comment]
ok lets go

**Comment by kpengboy** [comment]
...Would it have been possible to test this using `docker run` on some staffvm or similar?

**Pull request merged**
